services:
  - type: web
    name: maxfort-apps-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: myapps_sso
          property: connectionString
          
  - type: redis
    name: maxfort-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

databases:
  - name: myapps_sso
    databaseName: myapps_sso
    user: myapps_user
    plan: free 